// <auto-generated />
namespace winelegend.service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class passwordhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passwordhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202110240448386_passwordhistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
