// <auto-generated />
namespace winelegend.service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class languagemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(languagemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202110241004459_languagemigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
